######################################################################
# Automatically generated by qmake (3.0) Tue Mar 18 08:41:30 2014
######################################################################

TEMPLATE = app
TARGET = prodcons1
INCLUDEPATH += .
CONFIG += debug

# Input
SOURCES += prodcons1.cpp

HEADERS += \
    abstractbuffer.h \
    buffern.h
